import { desc, eq } from "drizzle-orm";
import { nanoid } from "nanoid";
import { z } from "zod";
import { fundMovements, fundPolicies, promotionalFunds } from "../../drizzle/schema";
import { calculateFundKpis, validateFundUsage } from "../../shared/commercial";
import { administratorProcedure, commercialProcedure, requireProfiles } from "../access";
import { getDb, recordAudit } from "../db";
import { router } from "../_core/trpc";

const policyInput = z.object({ name: z.string().min(3).max(180), percentage: z.number().positive().max(100), basisMonths: z.number().int().min(1).max(24), startsAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), endsAt: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional(), note: z.string().max(1000).optional() });

export const fundsRouter = router({
  summary: commercialProcedure.query(async () => { const db = await getDb(); if (!db) return calculateFundKpis([]); const funds = await db.select({ generatedValue: promotionalFunds.generatedValue, usedValue: promotionalFunds.usedValue, cancelledValue: promotionalFunds.cancelledValue }).from(promotionalFunds); return calculateFundKpis(funds.map(row => ({ generatedValue: Number(row.generatedValue), usedValue: Number(row.usedValue), cancelledValue: Number(row.cancelledValue) }))); }),
  policies: commercialProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(fundPolicies).orderBy(desc(fundPolicies.createdAt)) : []; }),
  list: commercialProcedure.query(async () => { const db = await getDb(); return db ? db.select().from(promotionalFunds).orderBy(desc(promotionalFunds.createdAt)).limit(100) : []; }),
  savePolicy: administratorProcedure.input(policyInput).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível."); if (input.endsAt && input.endsAt < input.startsAt) throw new Error("A vigência final não pode ser anterior à inicial."); await db.insert(fundPolicies).values({ name: input.name, percentage: String(input.percentage), basisMonths: input.basisMonths, startsAt: new Date(`${input.startsAt}T00:00:00Z`), endsAt: input.endsAt ? new Date(`${input.endsAt}T00:00:00Z`) : null, note: input.note || null, active: true }); await recordAudit({ id: nanoid(), userId: ctx.user.id, action: "CRIAR_POLITICA_VERBA", entity: "Política de verba", newValue: input }); return { success: true }; }),
  createFund: administratorProcedure.input(z.object({ customerId: z.number().int().positive(), policyId: z.number().int().positive().optional(), basePeriodStart: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), basePeriodEnd: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), baseRevenue: z.number().positive(), percentage: z.number().positive().max(100), availableFrom: z.string().regex(/^\d{4}-\d{2}-\d{2}$/), availableUntil: z.string().regex(/^\d{4}-\d{2}-\d{2}$/) })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível."); if (input.basePeriodEnd < input.basePeriodStart || input.availableUntil < input.availableFrom) throw new Error("Os períodos informados são inválidos."); const id = nanoid(); const generatedValue = Math.round(input.baseRevenue * input.percentage) / 100; await db.insert(promotionalFunds).values({ id, customerId: input.customerId, policyId: input.policyId ?? null, basePeriodStart: new Date(`${input.basePeriodStart}T00:00:00Z`), basePeriodEnd: new Date(`${input.basePeriodEnd}T00:00:00Z`), baseRevenue: String(input.baseRevenue), percentage: String(input.percentage), generatedValue: String(generatedValue), availableFrom: new Date(`${input.availableFrom}T00:00:00Z`), availableUntil: new Date(`${input.availableUntil}T00:00:00Z`) }); await db.insert(fundMovements).values({ id: nanoid(), fundId: id, type: "Geração", amount: String(generatedValue), responsible: ctx.user.name ?? undefined, note: "Geração controlada de verba promocional" }); await recordAudit({ id: nanoid(), userId: ctx.user.id, action: "GERAR_VERBA", entity: "Verba promocional", entityId: id, newValue: input }); return { id, generatedValue }; }),
  useFund: requireProfiles("Administrador", "Gerência Comercial", "Analista").input(z.object({ fundId: z.string().min(1), amount: z.number().positive(), campaign: z.string().min(3).max(255), purpose: z.enum(["Campanha promocional", "Redução de preço"]), targetCustomerId: z.number().int().optional(), note: z.string().max(1000).optional() })).mutation(async ({ ctx, input }) => { const db = await getDb(); if (!db) throw new Error("Banco de dados indisponível."); const [fund] = await db.select().from(promotionalFunds).where(eq(promotionalFunds.id, input.fundId)).limit(1); if (!fund) throw new Error("Verba não encontrada."); const available = Number(fund.generatedValue) - Number(fund.usedValue) - Number(fund.cancelledValue); validateFundUsage({ available, amount: input.amount, purpose: input.purpose, fundCustomerId: fund.customerId, targetCustomerId: input.targetCustomerId }); const nextUsed = Number(fund.usedValue) + input.amount; await db.update(promotionalFunds).set({ usedValue: String(nextUsed), status: nextUsed >= Number(fund.generatedValue) - Number(fund.cancelledValue) ? "Utilizada" : "Disponível" }).where(eq(promotionalFunds.id, fund.id)); await db.insert(fundMovements).values({ id: nanoid(), fundId: fund.id, type: "Utilização", amount: String(input.amount), campaign: input.campaign, responsible: ctx.user.name ?? undefined, note: input.note || null }); await recordAudit({ id: nanoid(), userId: ctx.user.id, action: "UTILIZAR_VERBA", entity: "Verba promocional", entityId: fund.id, newValue: { amount: input.amount, campaign: input.campaign, purpose: input.purpose } }); return { success: true, availableAfter: available - input.amount }; }),
});
