import { useMemo, useState } from "react";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { AlertTriangle, CheckCircle2, Scale } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useCommercialFilters } from "@/contexts/CommercialFilters";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const quantity = new Intl.NumberFormat("pt-BR", { maximumFractionDigits: 1 });
const tabs = ["byInvoice", "byDay", "byCustomer", "bySector", "byResponsible"] as const;
const tabNames = { byInvoice: "NF", byDay: "Dia", byCustomer: "Cliente", bySector: "Setor", byResponsible: "Responsável" };

export default function Conciliation() {
  const [activeTab, setActiveTab] = useState<(typeof tabs)[number]>("byInvoice");
  const { filters } = useCommercialFilters();
  const result = trpc.imports.reconciliation.useQuery(filters);
  const data = result.data;
  const detail = data?.details?.[activeTab];
  const pending = data?.status === "Pendente de classificação";
  const title = useMemo(() => detail?.label ?? tabNames[activeTab], [detail?.label, activeTab]);
  return <div><PageHeader eyebrow="CONCILIAÇÃO" title="Compare o arquivo com a operação importada" description="A conciliação segrega Venda, Devolução, Bonificação, Outros e Cancelado. Diferenças permanecem rastreáveis até a revisão."/>
    <section className="grid gap-4 md:grid-cols-3"><Card className="rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-5"><p className="text-xs text-[#76685a]">Status atual</p><div className="mt-3 flex items-center gap-2">{pending ? <AlertTriangle className="h-5 w-5 text-[#d06b15]"/> : <CheckCircle2 className="h-5 w-5 text-[#16803c]"/>}<strong className="text-lg text-[#33271f]">{data?.status ?? "Carregando"}</strong></div><p className="mt-2 text-xs text-[#796c60]">{pending ? `${data?.pending ?? 0} movimento(s) aguardam classificação.` : "Sem pendências de classificação no recorte."}</p></CardContent></Card><Card className="rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-5"><p className="text-xs text-[#76685a]">Faturamento líquido</p><strong className="mt-3 block text-2xl text-[#282018]">{money.format(data?.totals.netRevenue ?? 0)}</strong><p className="mt-2 text-xs text-[#796c60]">Vendas menos devoluções.</p></CardContent></Card><Card className="rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-5"><p className="text-xs text-[#76685a]">Peso líquido</p><strong className="mt-3 block text-2xl text-[#282018]">{quantity.format(data?.totals.netWeight ?? 0)} kg</strong><p className="mt-2 text-xs text-[#796c60]">Peso de vendas menos devolvido.</p></CardContent></Card></section>
    <Card className="mt-6 rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#fff0d5]"><Scale className="h-5 w-5 text-[#d06b15]"/></span><div><h3 className="font-bold text-[#30251d]">Resumo por movimento</h3><p className="text-xs text-[#776b60]">Os valores do caso de agosto de 2026 não são fixados: esta tela calcula somente o que foi importado.</p></div></div><div className="mt-5 overflow-auto rounded-xl border border-[#eee0cf]"><Table><TableHeader><TableRow><TableHead>Componente</TableHead><TableHead>R$</TableHead><TableHead>kg</TableHead><TableHead>Tratamento</TableHead></TableRow></TableHeader><TableBody><TableRow><TableCell className="font-medium">Vendas</TableCell><TableCell>{money.format(data?.totals.grossRevenue ?? 0)}</TableCell><TableCell>—</TableCell><TableCell><Badge variant="outline" className="border-[#c8e5d1] text-[#16803c]">Base positiva</Badge></TableCell></TableRow><TableRow><TableCell className="font-medium">Devoluções</TableCell><TableCell className="text-[#b42318]">{money.format(data?.totals.returnValue ?? 0)}</TableCell><TableCell>—</TableCell><TableCell><Badge variant="outline" className="border-[#efc4bf] text-[#b42318]">Subtrai do líquido</Badge></TableCell></TableRow><TableRow><TableCell className="font-medium">Bonificações</TableCell><TableCell>{money.format(data?.totals.bonusValue ?? 0)}</TableCell><TableCell>{quantity.format(data?.totals.bonusWeight ?? 0)}</TableCell><TableCell><Badge variant="outline" className="border-[#efd7b6] text-[#8b5b16]">Segregada</Badge></TableCell></TableRow><TableRow><TableCell className="font-medium">Outros / Não classificados</TableCell><TableCell>{money.format(data?.totals.otherValue ?? 0)}</TableCell><TableCell>—</TableCell><TableCell><Badge variant="outline" className="border-[#efd7b6] text-[#8b5b16]">Em revisão</Badge></TableCell></TableRow></TableBody></Table></div></CardContent></Card>
    <Card className="mt-6 rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-6"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-bold text-[#30251d]">Detalhamento de conciliação</p><p className="text-xs text-[#776b60]">Compare a composição financeira e física nos recortes operacionais.</p></div><div className="flex flex-wrap gap-2">{tabs.map(tab => <button key={tab} onClick={() => setActiveTab(tab)} className={`rounded-full px-3 py-1.5 text-xs font-semibold transition ${activeTab === tab ? "bg-[#d71920] text-white" : "border border-[#e7d2b4] bg-white text-[#6f5740]"}`}>{tabNames[tab]}</button>)}</div></div><div className="mt-5 overflow-auto rounded-xl border border-[#eee0cf]"><Table><TableHeader><TableRow><TableHead>{title}</TableHead><TableHead>Linhas</TableHead><TableHead>Vendas</TableHead><TableHead>Devoluções</TableHead><TableHead>Bonificações</TableHead><TableHead>Líquido</TableHead><TableHead>Peso</TableHead></TableRow></TableHeader><TableBody>{detail?.rows.length ? detail.rows.map(row => <TableRow key={row.label}><TableCell className="font-medium">{activeTab === "byDay" && row.label !== "Não informado" ? new Date(`${row.label}T12:00:00`).toLocaleDateString("pt-BR") : row.label}</TableCell><TableCell>{row.count}</TableCell><TableCell>{money.format(row.sales)}</TableCell><TableCell className="text-[#b42318]">{money.format(row.returns)}</TableCell><TableCell>{money.format(row.bonuses)}</TableCell><TableCell className="font-semibold">{money.format(row.netValue)}</TableCell><TableCell>{quantity.format(row.weightKg)} kg</TableCell></TableRow>) : <TableRow><TableCell colSpan={7} className="h-24 text-center text-sm text-[#7d6c5b]">Não há movimentos para detalhar neste recorte.</TableCell></TableRow>}</TableBody></Table></div></CardContent></Card>
  </div>;
}
