import { useState } from "react";
import { PageHeader } from "@/components/PageHeader";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { BadgeDollarSign, CircleAlert, LockKeyhole } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

const currency = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export default function Funds() {
  const summary = trpc.funds.summary.useQuery(); const policies = trpc.funds.policies.useQuery(); const funds = trpc.funds.list.useQuery(); const utils = trpc.useUtils(); const [name, setName] = useState("Política semestral 1%"); const [percentage, setPercentage] = useState("1"); const [basisMonths, setBasisMonths] = useState("6"); const [startsAt, setStartsAt] = useState(new Date().toISOString().slice(0, 10)); const [customerId, setCustomerId] = useState(""); const [baseRevenue, setBaseRevenue] = useState(""); const policy = trpc.funds.savePolicy.useMutation({ onSuccess: () => { utils.funds.policies.invalidate(); toast.success("Política de verba salva."); } }); const createFund = trpc.funds.createFund.useMutation({ onSuccess: () => { utils.funds.list.invalidate(); utils.funds.summary.invalidate(); toast.success("Verba promocional gerada."); } }); const useFund = trpc.funds.useFund.useMutation({ onSuccess: () => { utils.funds.list.invalidate(); utils.funds.summary.invalidate(); toast.success("Utilização registrada."); } });
  const data = summary.data;
  return <div><PageHeader eyebrow="VERBAS PROMOCIONAIS" title="Políticas parametrizáveis, saldo rastreável" description="A regra inicial proposta considera seis meses de compras e 1%, sem acúmulo e sem transferência entre clientes. A aprovação da política continua obrigatória."/>
    <section className="grid gap-4 lg:grid-cols-3"><Card className="rounded-3xl border-[#ecd8bd] bg-white lg:col-span-2"><CardContent className="p-6"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-2xl bg-[#fff0d5]"><BadgeDollarSign className="h-5 w-5 text-[#d06b15]"/></span><div><p className="font-bold text-[#34291f]">Política-base configurável</p><p className="mt-1 text-sm leading-6 text-[#776859]">Base de cálculo de seis meses, percentual sugerido de 1%, vigência semestral e expiração do saldo não utilizado. Qualquer alteração deve gerar versão e trilha de auditoria.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#fff8e8] p-4"><p className="text-xs text-[#7c6d5d]">Base</p><strong className="mt-2 block text-[#35291f]">Faturamento líquido</strong></div><div className="rounded-2xl bg-[#fff8e8] p-4"><p className="text-xs text-[#7c6d5d]">Percentual inicial</p><strong className="mt-2 block text-[#35291f]">1,00%</strong></div><div className="rounded-2xl bg-[#fff8e8] p-4"><p className="text-xs text-[#7c6d5d]">Acúmulo</p><strong className="mt-2 block text-[#35291f]">Não permitido</strong></div></div></CardContent></Card><Card className="rounded-3xl border-[#efd1ca] bg-[#fff9f7]"><CardContent className="p-6"><LockKeyhole className="h-5 w-5 text-[#b42318]"/><p className="mt-3 font-bold text-[#602a23]">Proteção comercial</p><p className="mt-2 text-sm leading-6 text-[#7e5d56]">A verba não pode ser utilizada como redução direta de preço e não pode ser transferida entre clientes.</p><Badge className="mt-4 bg-[#fde9e6] text-[#b42318] hover:bg-[#fde9e6]">Regra obrigatória</Badge></CardContent></Card></section>
    <section className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card className="rounded-2xl border-[#ecd8bd] bg-white"><CardContent className="p-4"><p className="text-xs text-[#7a6d60]">Verba gerada</p><strong className="mt-2 block text-lg">{currency.format(data?.generated ?? 0)}</strong></CardContent></Card><Card className="rounded-2xl border-[#ecd8bd] bg-white"><CardContent className="p-4"><p className="text-xs text-[#7a6d60]">Verba utilizada</p><strong className="mt-2 block text-lg">{currency.format(data?.used ?? 0)}</strong></CardContent></Card><Card className="rounded-2xl border-[#ecd8bd] bg-white"><CardContent className="p-4"><p className="text-xs text-[#7a6d60]">Saldo disponível</p><strong className="mt-2 block text-lg">{currency.format(data?.available ?? 0)}</strong></CardContent></Card><Card className="rounded-2xl border-[#ecd8bd] bg-white"><CardContent className="p-4"><p className="text-xs text-[#7a6d60]">Utilização</p><strong className="mt-2 block text-lg">{((data?.utilizationRate ?? 0) * 100).toLocaleString("pt-BR", { maximumFractionDigits: 1 })}%</strong></CardContent></Card></section>
    <Card className="mt-6 rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-6"><p className="font-bold text-[#34291f]">Políticas registradas</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input value={name} onChange={event => setName(event.target.value)} placeholder="Nome da política"/><Input value={percentage} onChange={event => setPercentage(event.target.value)} type="number" min="0.01" step="0.01" placeholder="Percentual"/><Input value={basisMonths} onChange={event => setBasisMonths(event.target.value)} type="number" min="1" placeholder="Meses-base"/><Input value={startsAt} onChange={event => setStartsAt(event.target.value)} type="date"/></div><Button className="mt-3 rounded-xl bg-[#d71920] hover:bg-[#b42318]" onClick={() => policy.mutate({ name, percentage: Number(percentage), basisMonths: Number(basisMonths), startsAt })} disabled={policy.isPending}>Salvar política</Button><div className="mt-5 space-y-2">{policies.data?.length ? policies.data.map(item => <div key={item.id} className="flex items-center justify-between rounded-xl bg-[#fff8e8] p-3 text-sm"><span><strong>{item.name}</strong> · {Number(item.percentage).toLocaleString("pt-BR", { maximumFractionDigits: 2 })}% · {item.basisMonths} meses</span><Badge className="bg-[#edf8ef] text-[#16803c] hover:bg-[#edf8ef]">{item.active ? "Ativa" : "Inativa"}</Badge></div>) : <p className="text-sm text-[#78695c]">Nenhuma política persistida ainda.</p>}</div></CardContent></Card>
    <Card className="mt-6 rounded-3xl border-[#ecd8bd] bg-white"><CardContent className="p-6"><p className="font-bold text-[#34291f]">Gerar verba por cliente</p><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><Input value={customerId} onChange={event => setCustomerId(event.target.value)} type="number" placeholder="ID do cliente"/><Input value={baseRevenue} onChange={event => setBaseRevenue(event.target.value)} type="number" placeholder="Faturamento-base"/><select className="h-9 rounded-lg border border-[#e4d0b3] bg-white px-3 text-sm" value={percentage} onChange={event => setPercentage(event.target.value)}>{policies.data?.map(item => <option key={item.id} value={String(item.percentage)}>{item.name} · {Number(item.percentage)}%</option>) ?? <option value="1">1%</option>}</select><Button className="rounded-xl bg-[#d71920] hover:bg-[#b42318]" onClick={() => createFund.mutate({ customerId: Number(customerId), baseRevenue: Number(baseRevenue), percentage: Number(percentage), basePeriodStart: startsAt, basePeriodEnd: startsAt, availableFrom: startsAt, availableUntil: startsAt })} disabled={!customerId || !baseRevenue || createFund.isPending}>Gerar verba</Button></div><p className="mt-2 text-xs text-[#78695c]">O cadastro usa um cliente existente e registra a geração na auditoria.</p><div className="mt-5 space-y-2">{funds.data?.length ? funds.data.map(fund => { const available = Number(fund.generatedValue) - Number(fund.usedValue) - Number(fund.cancelledValue); return <div key={fund.id} className="flex flex-col justify-between gap-2 rounded-xl bg-[#fff8e8] p-3 text-sm sm:flex-row sm:items-center"><span>Cliente #{fund.customerId} · disponível {currency.format(available)} · vence em {new Date(fund.availableUntil).toLocaleDateString("pt-BR")}</span><Button size="sm" variant="outline" onClick={() => { const amount = window.prompt("Valor para a campanha promocional:"); const campaign = window.prompt("Nome da campanha:"); if (amount && campaign) useFund.mutate({ fundId: fund.id, amount: Number(amount), campaign, purpose: "Campanha promocional", targetCustomerId: fund.customerId }); }}>Utilizar em campanha</Button></div>; }) : <p className="text-sm text-[#78695c]">Nenhuma verba persistida ainda.</p>}</div></CardContent></Card>
    <Card className="mt-6 rounded-3xl border-dashed border-[#e2c99f] bg-white/70"><CardContent className="grid min-h-48 place-items-center p-6 text-center"><div><CircleAlert className="mx-auto h-6 w-6 text-[#d06b15]"/><p className="mt-3 font-bold text-[#3b2d20]">{data?.generated ? "Acompanhe o saldo por cliente" : "Sem verbas calculadas"}</p><p className="mt-1 text-sm text-[#78695c]">As utilizações por redução direta de preço ou para outro cliente são bloqueadas no servidor.</p></div></CardContent></Card>
  </div>;
}
