import { Filter, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { type CommercialFilters, useCommercialFilters } from "@/contexts/CommercialFilters";

export function GlobalFilters() {
  const { filters, setFilters, clearFilters, activeCount } = useCommercialFilters();
  return <details className="relative"><summary className="flex h-9 cursor-pointer list-none items-center gap-2 rounded-xl border border-[#e5d1b3] bg-white px-3 text-xs font-semibold text-[#6b5642]"><Filter className="h-3.5 w-3.5"/>Filtros globais{activeCount ? <span className="grid h-4 min-w-4 place-items-center rounded-full bg-[#d71920] px-1 text-[10px] text-white">{activeCount}</span> : null}</summary><div className="absolute right-0 top-11 z-30 w-[min(92vw,560px)] rounded-2xl border border-[#ead6b9] bg-white p-4 shadow-[0_16px_45px_rgba(79,45,15,.18)]"><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs text-[#725f4d]">Data inicial<Input className="mt-1" type="date" value={filters.startDate ?? ""} onChange={event => setFilters({ ...filters, startDate: event.target.value || undefined })}/></label><label className="text-xs text-[#725f4d]">Data final<Input className="mt-1" type="date" value={filters.endDate ?? ""} onChange={event => setFilters({ ...filters, endDate: event.target.value || undefined })}/></label><label className="text-xs text-[#725f4d]">Geografia / região<Input className="mt-1" placeholder="Ex.: Amazonas" value={filters.commercialRegion ?? ""} onChange={event => setFilters({ ...filters, commercialRegion: event.target.value || undefined })}/></label><label className="text-xs text-[#725f4d]">Estrutura comercial / setor<Input className="mt-1" placeholder="Código ou setor" value={filters.sector ?? ""} onChange={event => setFilters({ ...filters, sector: event.target.value || undefined })}/></label><label className="text-xs text-[#725f4d]">Cliente<Input className="mt-1" placeholder="Código do cliente" value={filters.customerCode ?? ""} onChange={event => setFilters({ ...filters, customerCode: event.target.value || undefined })}/></label><label className="text-xs text-[#725f4d]">Produto<Input className="mt-1" placeholder="Código do produto" value={filters.productCode ?? ""} onChange={event => setFilters({ ...filters, productCode: event.target.value || undefined })}/></label><label className="text-xs text-[#725f4d] sm:col-span-2">Tipo de movimento<select className="mt-1 h-9 w-full rounded-lg border border-[#e4d0b3] bg-white px-3 text-sm" value={filters.category ?? ""} onChange={event => setFilters({ ...filters, category: event.target.value ? event.target.value as CommercialFilters["category"] : undefined })}><option value="">Todos os tipos</option><option>Venda</option><option>Devolução</option><option>Bonificação</option><option>Outros</option><option>Cancelado</option></select></label></div><Button variant="ghost" size="sm" className="mt-3 text-[#9d3a28]" onClick={clearFilters}><RotateCcw className="mr-1.5 h-3.5 w-3.5"/>Limpar filtros</Button></div></details>;
}
